"""Regenerate the small in-memory fallback probes (requires fontTools)."""
import base64
import io
import json
from pathlib import Path
from fontTools.fontBuilder import FontBuilder
from fontTools.pens.ttGlyphPen import TTGlyphPen

def probe_font(name, width):
    builder = FontBuilder(1000, isTTF=True)
    builder.setupGlyphOrder(['.notdef', 'probe'])
    builder.setupCharacterMap({32: 'probe'})
    pen = TTGlyphPen(None)
    pen.moveTo((50, 0)); pen.lineTo((width - 50, 0))
    pen.lineTo((width - 50, 700)); pen.lineTo((50, 700)); pen.closePath()
    glyph = pen.glyph()
    builder.setupGlyf({'.notdef': glyph, 'probe': glyph})
    builder.setupHorizontalMetrics({'.notdef': (width, 50), 'probe': (width, 50)})
    builder.setupHorizontalHeader(ascent=800, descent=-200)
    builder.setupNameTable({'familyName': name, 'styleName': 'Regular',
        'uniqueFontIdentifier': name, 'fullName': name, 'psName': name,
        'licenseDescription': 'Unlicense'})
    builder.setupOS2(sTypoAscender=800, sTypoDescender=-200, usWinAscent=800, usWinDescent=200)
    builder.setupPost(); builder.setupMaxp()
    builder.font['head'].created = builder.font['head'].modified = 2082844800
    builder.font.recalcTimestamp = False
    output = io.BytesIO(); builder.font.save(output)
    return base64.b64encode(output.getvalue()).decode('ascii')

root = Path(__file__).resolve().parents[1]
data = [probe_font('FontFourierProbeA', 400), probe_font('FontFourierProbeB', 900)]
target = root / 'assets' / 'glyph-probes.js'
target.write_text('// Generated by scripts/generate-glyph-probes.py; Unlicense.\n'
    + 'window.FontFourierGlyphProbes = ' + json.dumps(data) + ';\n', encoding='utf-8')
